#!/bin/sh
source /etc/fang_hacks.cfg
DISABLE_CLOUD="${DISABLE_CLOUD:-0}"

echo "Load drivers..."

#/usr/bin/timing_cali &

modprobe snx_gpio
#modprobe snx_pwm
#modprobe snx_rtc
modprobe snx_i2s_gpio
modprobe snx_nvram

/etc/init.d/videomdprob.sh &
/etc/init.d/audmdprob.sh &

#power on sensor
/bin/gpio_ms1 -n 6 -m 1 -v 1
modprobe mt7601Usta
#modprobe snx_uvc


#modprobe snx_vo
modprobe snx_sd
if [ "$DISABLE_CLOUD" -eq 0 ]; then
  modprobe snx_wdt
fi
modprobe 8188eu
#hwclock -s

if [ -f /lib/modules/2.6.35.12/kernel/drivers/bcmdhd.ko ]; then
	#/bin/bcmdl -n /usr/share/WUBB-738GN_4.2/Wi-Fi/nvram_wubb-743gn.nvm /usr/share/WUBB-738GN_4.2/Wi-Fi/fw_bcm43143b0_mfg.bin.trx -C 10
	/bin/bcmdl -n /usr/share/WUBB-738GN_4.2/Wi-Fi/nvram_wubb-743gn.nvm /usr/share/WUBB-738GN_4.2/Wi-Fi/cooee.bin.trx -C 10
	modprobe bcmdhd
fi

# Start all init scripts in /etc/init.d
# executing them in numerical order.
#
for i in /etc/init.d/S??* ;do

     # Ignore dangling symlinks (if any).
     [ ! -f "$i" ] && continue

     case "$i" in
	*.sh)
	    # Source shell script for speed.
	    (
		trap - INT QUIT TSTP
		set start
		. $i
	    )
	    ;;
	*)
	    # No sh extension, so fork subprocess.
	    $i start
	    ;;
    esac
done

# Here start our services
/etc/init.d/rc.local &

/usr/bin/singleBoadTest/singleBoadTest

if [ "$DISABLE_CLOUD" -eq 0 ]; then
  /usr/bin/iSC3S/iSC3S &
fi