#!/bin/sh

if [ $ACTION = "add" ]; then
	mkdir -p /media/$MDEV

	grep -w "3" /proc/mmc/pwroff
	status = $?

	if [ ! -x /tmp/mmc.all.log ] || [ $status == 0 ]; then
#		sleep 1

		ps > /tmp/mmc.ps.log
		grep -w "lsblk" /tmp/mmc.ps.log
		if [ $? == 0 ]; then
			echo "1" > /tmp/mmc.ps2.log
			exit 0
		fi

		grep -w "1" /proc/mmc/removal
		if [ $? == 0 ]; then
			exit 0
		fi

		grep -w "1" /proc/mmc/pwroff
		if [ $? == 0 ]; then
			killall -9 lsblk
			exit 0
		fi
		
		sleep 1	
#		ps > /tmp/mmc.ps.log
#		grep -w "lsblk" /tmp/mmc.ps.log
#		if [ $? == 0 ]; then
#			echo "1" > /tmp/mmc.ps2.log
#			exit 0
#		fi

#		echo "2" > /tmp/mmc.ps2.log

		echo "0x1" >/proc/mmc/pwroff
		lsblk -o KNAME,FSTYPE /dev/mmc* > /tmp/lsblk.log
		echo "0x0" >/proc/mmc/pwroff

		grep "mmc" /tmp/lsblk.log > /tmp/mmc.all.log

		grep "vfat" /tmp/mmc.all.log > /tmp/mmc.vfat.log
		grep "exfat" /tmp/mmc.all.log > /tmp/mmc.exfat.log
		grep "ntfs" /tmp/mmc.all.log > /tmp/mmc.ntfs.log
		grep "ext2" /tmp/mmc.all.log > /tmp/mmc.ext2.log
	fi

	grep -w $MDEV /tmp/mmc.vfat.log
	if [ $? == 0 ]; then
#		sleep 1
		grep -w "1" /proc/mmc/removal
		if [ $? == 0 ]; then
			exit 0
		fi

		mount -t vfat -o rw /dev/$MDEV /media/$MDEV
		echo "1" > /tmp/$MDEV
		mount -o remount,rw /dev/$MDEV
		echo "1" > /tmp/guozhixin
		if [ -f /media/$MDEV/snx_autorun.sh ]; then
			echo "find snx_autorun.sh" > /dev/console
			/media/$MDEV/snx_autorun.sh
		fi                   
		exit 0
	fi
	
	grep -w $MDEV /tmp/mmc.exfat.log
	if [ $? == 0 ]; then
		mount /dev/$MDEV /media/$MDEV
		#mount.exfat-fuse /dev/$MDEV /media/$MDEV
		echo "1" > /tmp/$MDEV
		mount -o remount,rw /dev/$MDEV
		echo "2" > /tmp/guozhixin
		if [ -f /media/$MDEV/snx_autorun.sh ]; then
			echo "find snx_autorun.sh" > /dev/console
			/media/$MDEV/snx_autorun.sh
		fi
		exit 0
	fi
	
	grep -w $MDEV /tmp/mmc.ntfs.log
	if [ $? == 0 ]; then
		ntfs-3g /dev/$MDEV /media/$MDEV
		echo "1" > /tmp/$MDEV
		#mount -o remount,rw /dev/$MDEV
		echo "3" > /tmp/guozhixin
		if [ -f /media/$MDEV/snx_autorun.sh ]; then
			echo "find snx_autorun.sh" > /dev/console
			/media/$MDEV/snx_autorun.sh
		fi  
		exit 0
	fi

	grep -w $MDEV /tmp/mmc.ext2.log
	if [ $? == 0 ]; then
		mount /dev/$MDEV /media/$MDEV
		echo "1" > /tmp/$MDEV
		exit 0
	fi
else
	umount /dev/$MDEV
	rm -rf /media/$MDEV
	rm -f /tmp/$MDEV
	rm -f /tmp/guozhixin
	echo "0x3" >/proc/mmc/pwroff
fi
