#!/bin/sh
                                     
source /etc/fang_hacks.cfg
if [ "$DISABLE_CLOUD" -eq 0 ]; then
	echo "Stopping Cloud applications..."
	pid="$(pidof test_UP)"
	if [ $? -eq 0 ]; then
	  echo "  test_UP[$pid]"
	  kill $pid
	fi

	pid="$(pidof iSC3S)"
	if [ $? -eq 0 ]; then
	  echo "  iSC3S[$pid]"
	  kill -9 $pid
	fi

	pid="$(pidof iCamera)"
	if [ $? -eq 0 ]; then
	  echo "  iCamera[$pid]"
	  kill -9 $pid
	fi

	pid="$(pidof miio_client)"
	if [ $? -eq 0 ]; then
	  echo "  miio_client[$pid]"
	  kill $pid
	fi

	# snx_wdt needs some persuading
	count=0
	while [ $count -lt 30 ]; do
	  if [ $count -eq 0 ]; then modprobe -rf snx_wdt >> /tmp/hacks.log 2>&1; else modprobe -rf snx_wdt; fi
	  if [ $? -ne 0 ]; then
	  	echo "Waiting to unload snx_wdt"
	  	count=$(expr $count + 1)
	    sleep 2
	  else
	  	echo "Module snx_wdt unloaded ($count)"
	  	break
	  fi
	done
else
	if ps |grep -E 'iSC3S|iCamera|miio_client' |grep -v grep; then
		echo "Cloud disabled but apps still running!"
	else
		echo "Cloud is disabled"
	fi
fi