#!/bin/sh
PIDFILE="/var/run/dropbear.pid"

status()
{
  pid="$(cat "$PIDFILE" 2>/dev/null)"
  if [ "$pid" ]; then
    kill -0 "$pid" 2>/dev/null && echo "PID: $pid" || return 1
  fi
}

start() 
{
  echo "Starting dropbear on port 22..."
  if [ ! -d /etc/dropbear ]; then mkdir /etc/dropbear; fi
  dropbear -R -P "$PIDFILE" &
}

stop()
{
  pid="$(cat "$PIDFILE" 2>/dev/null)"
  if [ "$pid" ]; then
     kill $pid || rm "$PIDFILE"
  fi
}

if [ $# -eq 0 ]; then
  start
else
  case $1 in start|stop|status)
    $1
    ;;
  esac
fi
