#!/bin/sh
PIDFILE="/var/run/fang-ftpd.pid"
status()
{
  pid="$(cat "$PIDFILE" 2>/dev/null)"
  if [ "$pid" ]; then
    kill -0 "$pid" >/dev/null && echo "$pid" || return 1
    return 0
  else
    return 1
  fi
}

stop()
{
  pid="$(cat "$PIDFILE" 2>/dev/null)"
  if [ "$pid" ]; then
     kill $pid
     rm "$PIDFILE"
  fi
}

start()
{
  echo "Starting FTPd..."
  tcpsvd -E 0.0.0.0 21 ftpd -w /media/mmcblk0p2/data </dev/null >/dev/null 2>&1 &
  echo "$!" > "$PIDFILE"
}

if [ $# -eq 0 ]; then
  start
else
  case $1 in start|stop|status)
    $1
    ;;
  esac
fi
