#!/bin/sh
PIDFILE="/var/run/telnetd.pid"

status()
{
  pid="$(cat "$PIDFILE" 2>/dev/null)"
  if [ "$pid" ]; then
    kill -0 "$pid" 2>/dev/null && echo "PID: $pid" || return 1
  else
    echo "no pid"
  fi
}

start() 
{
  echo "Starting telnetd on port 2323..."
  telnetd -p 2323 -l fang_login &
  sleep 1
  pidof telnetd > "$PIDFILE"
}

stop()
{
  pid="$(cat "$PIDFILE" 2>/dev/null)"
  if [ "$pid" ]; then
     kill $pid || rm "$PIDFILE"
  fi
}

if [ $# -eq 0 ]; then
  start
else
  case $1 in start|stop|status)
    $1
    ;;
  esac
fi
