#!/bin/sh

echo "Content-type: text/html"
echo ""

cat << EOF

<html>
<head>
<title>Fang Hacks</title>
<style type="text/css">
body { background-color: #B0E0E6; font-family: verdana, sans-serif; }
.err { color: red; }
hr { height: 1px; border: 0; border-top: 1px solid #aaa; }
button, input[type=submit] { background-color: #ddeaff; }
.tbl { border-collapse: collapse; border-spacing: 0;}
.tbl th { text-align: left; vertical-align: top; font-weight: bold; padding: 10px 5px; border-style: solid; border-width: 1px; overflow: hidden; word-break: normal; }
.tbl td { padding: 10px 5px; border-style: solid; border-width: 1px; overflow: hidden; word-break: normal; }
</style>
<head>
<body>
<h1>Save RTSP Config</h1>
<hr/>
<button title='Status page' type='button' onClick="window.location.href='status'">Status</button>
<button title='Reboot the device' type='button' onClick="window.location.href='action?cmd=reboot'">Reboot</button>
<button title='Info' type='button' onClick="window.location.href='scripts'">Scripts</button>
<button title='View /tmp/hacks.log' type='button' onClick="window.location.href='action?cmd=showlog'">View log</button>
<button title='Network' type='button' onClick="window.location.href='network'">Network</button>
<button title='Configure RTSP' type='button' onClick="window.location.href='cfg_rtsp'">Config RTSP</button>
<hr/>
<div style='clear: both;'>
EOF
CMDLINE=$(echo $QUERY_STRING | sed 's/^.....//' | sed -e "s/\+/ /g" | sed -e "s/\%3E/>/g" | sed -e "s/\%26/\&/g" | sed -e "s/\%24/\$/g")
#don't save the file if it doesn't include _server in the command
if [ -z "${CMDLINE##*_server*}" ]; then
  sed -i '/_server/c\'"$CMDLINE" /media/mmcblk0p2/data/etc/scripts/20-rtsp-server 2>&1
  echo "File saved, 20-rtsp-server script must be restarted for changes to take effect"
else
  echo "error"
fi
cat << EOF
</div>
<div style='clear: both;'>

</div>
</body>
</html>
EOF

