#!/bin/sh

echo "Content-type: text/html"
echo ""
source func.cgi
cat << EOF
<html>
<head>
<title>Fang Hacks</title>
<head>
<style type="text/css">
body { background-color: #B0E0E6; }
.err { color: red; }
.tbl { border-collapse: collapse; border-spacing: 0;}
.tbl th { text-align: left; vertical-align: top; font-weight: normal; padding: 10px 5px; border-style: solid; border-width: 1px; overflow: hidden; word-break: normal; }
.tbl td { padding: 10px 5px; border-style: solid; border-width: 1px; overflow: hidden; word-break: normal; }
</style>
<body>
<h1>Boot Scripts</h1>
<hr/>
<button title='Status page' type='button' onClick="window.location.href='status'">Status</button>
<button title='Reboot the device' type='button' onClick="window.location.href='action?cmd=reboot'">Reboot</button>
<button title='Network' type='button' onClick="window.location.href='action?cmd=network'">Network</button>
<button title='View /tmp/hacks.log' type='button' onClick="window.location.href='action?cmd=showlog'">View log</button>
<hr/>
EOF

SCRIPT_HOME="/media/mmcblk0p2/data/etc/scripts"
source "/media/mmcblk0p2/data/etc/profile" >/dev/null 2>&1
if [ -n "$F_script" ]; then
  script="${F_script##*/}"
  if [ -e "$SCRIPT_HOME/$script" ]; then
    case "$F_cmd" in
      start)
        echo "Running script '$script'...<br/>"
        echo "<pre>$($SCRIPT_HOME/$script 2>&1)</pre>"
        ;;  
      disable)
        echo "Disable script '$script'...<br/>"
        chmod a-x "$SCRIPT_HOME/$script" 2>&1
        ;;
      stop)
        echo "Stop script '$script'...<br/>"
        $SCRIPT_HOME/$script stop 2>&1 && echo "OK" || echo "NOK"
        echo "<br/>"
        ;;
      enable)
        echo "Enable script '$script'...<br/>"
        chmod a+x "$SCRIPT_HOME/$script" 2>&1
        ;;
      view)
        echo "Contents of script '$script':<br/>"
        echo "<pre>$(cat $SCRIPT_HOME/$script 2>&1)</pre>"
        ;;
      *)
        echo "Unsupported command '$F_cmd'<br/>"
        ;;
    esac
    echo "<hr/>"
  else
    echo "$F_script is not a valid script!<br/>"
  fi
fi

if [ ! -d "$SCRIPT_HOME" ]; then
  echo "No scripts found in $SCRIPT_HOME<br/>"
else
  SCRIPTS=$(ls -A "$SCRIPT_HOME")
  echo "<table class='tbl'>"
  echo "<tr><th>Service</th><th>Status</th><th/><th/><th/></tr>"
  for i in $SCRIPTS; do
    echo "<tr>"
    echo "<td>$i</td>"
    if [ -x "$SCRIPT_HOME/$i" ]; then
      if [ $(grep "^status\(\)" "$SCRIPT_HOME/$i") ]; then
        pid="$($SCRIPT_HOME/$i status)"
        if [ "$pid" ]; then echo "<td bgcolor='green'>PID: $pid</td>"; else echo "<td bgcolor='red'>NOK</td>"; fi
      else
        echo "<td/>"
      fi

      if [ $(grep "^start\(\)" "$SCRIPT_HOME/$i") ]; then
        if [ -z "$pid" ]; then
          echo "<td><button title='Start script' type='button' onClick=\"window.location.href='scripts?cmd=start&script=$i'\">Start</button</td>"
        else
          echo "<td><button title='Already running' disabled>Start</button>"
        fi
      else
        echo "<td><button title='Run script' type='button' onClick=\"window.location.href='scripts?cmd=start&script=$i'\">Run</button></td>"
      fi

      if [ $(grep "^stop\(\)" "$SCRIPT_HOME/$i") ]; then
        if [ -n "$pid" ]; then
          echo "<td><button title='Stop script' type='button' onClick=\"window.location.href='scripts?cmd=stop&script=$i'\">Stop</button></td>"
        else
          echo "<td><button title='Not running' disabled>Stop</button>"
        fi
      else
        echo "<td></td>"
      fi
      echo "<td><button title='Disable script' type='button' onClick=\"window.location.href='scripts?cmd=disable&script=$i'\">Disable</button></td>"
     else
      echo "<td/>"
      echo "<td><button title='Enable script' type='button' onClick=\"window.location.href='scripts?cmd=enable&script=$i'\">Enable</button></td>"
      echo "<td/><td/>"
    fi
    echo "<td><button title='View script' type='button' onClick=\"window.location.href='scripts?cmd=view&script=$i'\">View</button></td>"
    echo "</tr>"
  done
  echo "</table>"
fi

cat << EOF
<hr/>
</body>
</html>
EOF
